Numpy Introduction

# What is an Array?

An array is a collection of elements of the same data type stored in a single variable. In other words, an array is a container that holds multiple values of the same type, such as numbers, strings, or objects.

Think of an array like a box that can hold multiple items. Each item in the box is called an element, and each element has a specific position in the box, known as an index.

In [2]:
# import Libraries
import numpy as np


In [3]:
# 
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [4]:
# 
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [5]:
# Convert it to 2D
a2 = a[np.newaxis, :]
print(a2)

[[0 1 2 3 4 5]]


In [6]:
a2.shape

(1, 6)

In [7]:
a3 = a[:, np.newaxis]
print(a3)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [8]:
# 3D Array
a4 = a[np.newaxis, :, np.newaxis]
print(a4)
a4.shape

[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]]]


(1, 6, 1)

# Creating array with numpy

In [9]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
b = np.array([(1, 2, 3, 4, 5, 6, 7),(4, 5, 6, 7, 8, 9, 10)])

In [10]:
print(a)
a.shape
a.dtype

[1 2 3 4 5 6 7]


dtype('int64')

In [11]:
print(b)
b.shape
b.dtype

[[ 1  2  3  4  5  6  7]
 [ 4  5  6  7  8  9 10]]


dtype('int64')

# Initialize Arrays

In [12]:
zeros = np.zeros((3, 4)) # rows and columns
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
zeros.dtype

dtype('float64')

In [14]:
ones = np.ones((2, 5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
ones.dtype

dtype('float64')

In [16]:
full = np.full((2, 3), 5)
full

array([[5, 5, 5],
       [5, 5, 5]])

In [17]:
full.dtype

dtype('int64')

In [18]:
full1 = np.full((2, 3), 7.5)
full1

array([[7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5]])

In [19]:
full1.dtype

dtype('float64')

# identity MAtrix

In [20]:
# creating identity matrix
identity = np.eye(5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
identity.dtype # tells the type of data elements

dtype('float64')

In [22]:
type(identity) # tells the type of Array

numpy.ndarray

# Attributes of Array

In [32]:
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8,  9, 10]])

In [23]:
b.shape

(2, 7)

In [29]:
len(b) # length of elements in an array

2

In [30]:
b.size # number of elements in an array

14

In [31]:
b.ndim # number of dimensions

2

# basic operations


In [33]:
g = a-b
g

array([[ 0,  0,  0,  0,  0,  0,  0],
       [-3, -3, -3, -3, -3, -3, -3]])

In [34]:
# addition of two dimension arrray
h = a+b
h

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [37]:
# another method
h1 = np.add(a,b)
h1

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [38]:
# multiplication
i = a*b
i

array([[ 1,  4,  9, 16, 25, 36, 49],
       [ 4, 10, 18, 28, 40, 54, 70]])

In [39]:
# Division
j = a/b
j

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
        0.66666667, 0.7       ]])

In [40]:
# square of each element
k = a**2
k

array([ 1,  4,  9, 16, 25, 36, 49])

In [41]:
a

array([1, 2, 3, 4, 5, 6, 7])