# Numpy (Part2)

In [1]:
import numpy as np

In [7]:
#Creating empty array of two by three
empty_array = np.empty((2,3))
print(empty_array)

[[4.45057637e-308 8.90104239e-307 1.11255866e-306]
 [1.33511561e-306 1.11261027e-306 4.94065646e-322]]


In [11]:
# printing indexwise
print(empty_array[0]) # 0 is the first row of array

[4.45057637e-308 8.90104239e-307 1.11255866e-306]


In [13]:
x = np.arange(6) # its a-range not arrange
x

array([0, 1, 2, 3, 4, 5])

In [17]:
# even numbers from  to 2
even = np.arange(0, 23, 2) # 0, 0+2, 2+2, 4+2, and so on
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [18]:
# arrays of odd numbers from 0 to 23
odd = np.arange(1, 23, 2) # 1, 1+2, 3+2, 5+2, and so on 
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [22]:
# specific difference between numbers
diff = np.arange(0, 23, 0.515) # 0.515 is diff bet num

In [29]:
# LinSpace is used to linear trend
lspace = np.linspace(0, 20, 170000000) # 170000000 is num total numbers
lspace

array([0.00000000e+00, 1.17647060e-07, 2.35294119e-07, ...,
       1.99999998e+01, 1.99999999e+01, 2.00000000e+01])

In [32]:
# creating array by giving dtatatype
x = np.arange(6, dtype = np.float64)
x.dtype

dtype('float64')

In [33]:
# creating array by giving dtatatype in linspace
lspace = np.linspace(0, 20, 17, dtype = np.float64)
lspace.dtype

dtype('float64')

In [35]:
# define the data type of aaray
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [36]:
# define the data type of aaray
x = np.ones(2, dtype=np.float64)
x

array([1., 1.])

In [38]:
# soring an aray
# creating 
arr = np.array([1, 2, 3, 4, 5])
# sorting
np.sort(arr)
arr

array([1, 2, 3, 4, 5])

# Concatenation

In [42]:
# Creating two one dimensional arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
# concatenation these arrays
np.concatenate((a, b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
# Concatenate Two Dimensional Arrays
x = np.array([[1, 2], [3, 4]]) # 2x2 array
y = np.array([[5, 6], [7, 8]]) # 1x2 array
# concatenate
z = np.concatenate((x, y))
z


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [52]:
# Concatenate Two Dimensional Arrays and using axis
w = np.array([[5, 1], [7, 1]]) # 2x2 array
x = np.array([[1, 2], [3, 4]]) # 2x2 array
# concatenate
z1= np.concatenate((w, x), axis=1)
z1


array([[5, 1, 1, 2],
       [7, 1, 3, 4]])

In [53]:
x.ndim

2

Creating 3D Array

In [62]:
# Create a # 3D Array
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim

3

In [63]:
len(array_example)

3

In [64]:
array_example.size 

24

In [65]:
array_example.dtype

dtype('int64')

In [72]:
array_example.shape # 3 sets and 2 rows and 4 columns

(3, 2, 4)

In [74]:
# create 3D array of size (3,1,4)
a1 = np.array([[[0, 1, 2, 3]],
                           [[4, 5, 6, 7]],
                           [[0, 1, 2, 3]]])
a1

array([[[0, 1, 2, 3]],

       [[4, 5, 6, 7]],

       [[0, 1, 2, 3]]])

In [78]:
a1.shape

(3, 1, 4)

Reshape

In [77]:
# reshape array
a2 = a1.reshape(6, 2)
a2.shape

(6, 2)

In [79]:
a1

array([[[0, 1, 2, 3]],

       [[4, 5, 6, 7]],

       [[0, 1, 2, 3]]])

In [80]:
a2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [0, 1],
       [2, 3]])

In [82]:
a2.reshape(3,1,4)
a2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [0, 1],
       [2, 3]])

In [83]:
# create a 1D array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a.shape

(8,)

In [87]:
# convert it to 2D array
b = a[np.newaxis, :]
b.shape

(1, 8)

In [88]:
c = a[:, np.newaxis]
c.shape

(8, 1)

# Indexing and Slicing

In [90]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [93]:
a[2] # shows 3 of the data

np.int64(3)

In [95]:
a[-4:] # shows last 4 data

array([5, 6, 7, 8])

In [96]:
a[-4:-2] # shows last 4 to 2

array([5, 6])

In [97]:
a[1:] # shows 1 to last

array([2, 3, 4, 5, 6, 7, 8])

In [98]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [99]:
b[0] # shows first row

array([1, 2, 3, 4])

In [101]:
b[1] # shows second row

array([5, 6, 7, 8])

In [103]:
b[1:,1:] # shows second row and second column

array([[ 6,  7,  8],
       [10, 11, 12]])

In [104]:
b[b>5] # shows all values greater than 5

array([ 6,  7,  8,  9, 10, 11, 12])

In [105]:
b[b<5] # shows all values less than 5

array([1, 2, 3, 4])

In [106]:
b[b==5] # shows all values equal to 5

array([5])

In [108]:
b[b%2==0] # shows all values that are even

array([ 2,  4,  6,  8, 10, 12])

In [109]:
b[b%2==1] # shows all values that are odd   

array([ 1,  3,  5,  7,  9, 11])

In [110]:
b[(b > 2) & (b < 10)] # shows all values that are greater than 2 and less than 10

array([3, 4, 5, 6, 7, 8, 9])

In [114]:
b[(b > 2) | (b < 10)] # shows all values that are greater than 2 or less than 10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [115]:
b[(b>2)&(b<11)&(b%2==0)] # shows all values that are greater than 2 and less than 11 and even

array([ 4,  6,  8, 10])