# Numpy indexing and slicing

In [66]:
import numpy as np
# create ana array
a = np.array([1, 2, 3, 4, 5, 6, 7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [67]:
a[0]

np.int64(1)

In [68]:
# creating even number array
b = np.arange(0,12,2)
b

array([ 0,  2,  4,  6,  8, 10])

In [69]:
b[2]

np.int64(4)

In [70]:
# reshape 
c= b.reshape(2, 3)
c

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [71]:
c[0] # 0th row

array([0, 2, 4])

In [72]:
c[1]# 1st row

array([ 6,  8, 10])

In [73]:
c[:4] # : is range

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [51]:
c

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [52]:
c[c>5]

array([ 6,  8, 10])

In [53]:
c[(c>5)&(c>7)]

array([ 8, 10])

Markdown table summarizing Python conditional and boolean operators:

| Operator | Type       | Definition                                                             | Example  |
|----------|------------|-----------------------------------------------------------------------|----------|
| `==`     | Conditional| Checks if two values are equal.                                       | `a == b` |
| `!=`     | Conditional| Checks if two values are not equal.                                   | `a != b` |
| `>`      | Conditional| Checks if the left value is greater than the right value.            | `a > b`  |
| `<`      | Conditional| Checks if the left value is less than the right value.               | `a < b`  |
| `>=`     | Conditional| Checks if the left value is greater than or equal to the right value.| `a >= b` |
| `<=`     | Conditional| Checks if the left value is less than or equal to the right value.   | `a <= b` |
| `and`    | Boolean    | Returns `True` if both operands are true.                            | `a and b`|
| `or`     | Boolean    | Returns `True` if at least one operand is true.                      | `a or b` |
| `not`    | Boolean    | Returns `True` if the operand is false.                              | `not a`  |

Making an array from a data or another array

In [54]:
a = np.arange(0, 222, 5)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [55]:
len(a)

45

In [56]:
array1 = a[40:45]
array1

array([200, 205, 210, 215, 220])

Stacking

In [57]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
b = np.array([8, 9, 10, 11, 12, 13, 14])


In [58]:
# vertical stack
c = np.vstack((a,b))
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [59]:
# Horizontally Stack
d = np.hstack((a,b))
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [60]:
d = d.reshape(2,7)
d

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

---
Matrix or Matrices

In [61]:
# Creating a 2x3 matrix
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
# Create a matrix of big dimension
b = np.arange(0,100,2).reshape(5,10)
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [80]:
# # slicing a matrix
# b[:,:] # all rows and all cols

In [81]:
# # slicing a matrix
# b[0:3,:] # 1st row to 3rd row and all cols

In [82]:
# # slicing a matrix
# b[0:3,3:5] # 1st row to 3rd row and 3rd col to 5th col

In [83]:
# slicing a matrix
e = b[0:3,3:5] # 1st row to 3rd row and 3rd col to 5th col
e

array([[ 6,  8],
       [26, 28],
       [46, 48]])

In [84]:
b.max()

np.int64(98)

In [85]:
b.min()

np.int64(0)

In [90]:
b.min(axis=0) # min of each col

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [91]:
b.min(axis=1) # min of each row

array([ 0, 20, 40, 60, 80])

In [92]:
b.sum()

np.int64(2450)

In [93]:
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [96]:
b.max(axis=0)# max of each col

array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [97]:
b.max(axis=1)# max of each row

array([18, 38, 58, 78, 98])

Addition and deletion

In [100]:
m = np.arange(0,20,2).reshape(5,2)
m

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [101]:
m+np.array([20,22])

array([[20, 24],
       [24, 28],
       [28, 32],
       [32, 36],
       [36, 40]])

In [103]:
np.vstack((m, np.array([42,44])))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [42, 44]])

In [104]:
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [106]:
np.flip(b) # flip the matrix

array([[98, 96, 94, 92, 90, 88, 86, 84, 82, 80],
       [78, 76, 74, 72, 70, 68, 66, 64, 62, 60],
       [58, 56, 54, 52, 50, 48, 46, 44, 42, 40],
       [38, 36, 34, 32, 30, 28, 26, 24, 22, 20],
       [18, 16, 14, 12, 10,  8,  6,  4,  2,  0]])